{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    release: {{ .Values.appname }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.rules }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ .appname }}
              servicePort: {{ default "http" .servicePort }}
  {{- end }}
  {{- end }}

