apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.appname }}
    release: {{ .Values.appname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appname }}
    release: {{ .Values.appname }}

